(define ka 0.583)
(define kr 0.364)
(define e 2.71828)
(define (f x)
 (+ (* 0.2 ka (expt e (* -1 ka x)))
    (* (- 0.47 (* 0.2 (expt e (* -1 ka x))))
	   (- (* kr (expt e (* -1 kr x)))
		  (* ka (expt e (* -1 ka x))))
	   (/ 1 (expt e (* -1 kr x))))))

(define (g x)
 (+ (expt e (* -1 ka x)) 
    (* (/ (* ka (expt e (* -1 ka x)))
		  (- (* ka (expt e (* -1 ka x)))
		     (* kr (expt e (* -1 kr x)))))
	   (- (expt e (* -1 kr x))
		  (expt e (* -1 ka x))))
	(/ -17.7 7.54)))
