(define (integers_from n)
 (cons n (delay (integers_from (+ n 1)))))
(define primes
 (cons 2 (delay (stream-filter prime? (integers_from 3)))))
(define (prime? n)
 (define (iter ps)
  (cond ((> (* (car ps) (car ps)) n ) #T)
        ((= (mod n (car ps)) 0) #F)
		(else (iter (force (cdr ps))))))
 (iter primes))
