 (define (divisor x n)
  (cond ((= (* x x) n) 1)
        ((> (* x x) n) 0)
		((= 0 (mod n x)) (+ 2 (divisor (+ x 1) n))) 
		(else (divisor (+ x 1) n))))
(define (num_Divisor n)
 (divisor 1 n))
(define (over n x)
 (cond ((> (num_Divisor (/ (* n (+ n 1)) 2)) x) (/ (* n (+ n 1)) 2))
       (else (over (+ n 1) x))))
